export enum StandingLeagueId {
  ENGLAND_PREMIER_LEAGUE = "39",
  GERMANY_BUNDESLIGA = "78",
  GERMANY_BUNDESLIGA_2 = "79",
  ITALY_SERIE_A = "135",
  SPAIN_LA_LIGA = "140",
  FRANCE_LIGUE_1 = "61"
}
